In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/ELCOT/Downloads/crop_yield.csv")

In [5]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [6]:
df.tail()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [7]:
print("Size:", df.size)

Size: 196890

In [8]:
print("Shape:", df.shape)

Shape: (19689, 10)

In [9]:
print("Columns:", df.columns)

Columns: Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='str')

In [11]:
print(df.dtypes)

Crop                   str
Crop_Year            int64
Season                 str
State                  str
Area               float64
Production           int64
Annual_Rainfall    float64
Fertilizer         float64
Pesticide          float64
Yield              float64
dtype: object

In [12]:
df.drop_duplicates(inplace=True)

df["Crop_Year"] = pd.to_datetime(
    df["Crop_Year"].astype(str) + "-01-01"
)

print(df.dtypes)
print(df.head())

Crop                          str
Crop_Year          datetime64[us]
Season                        str
State                         str
Area                      float64
Production                  int64
Annual_Rainfall           float64
Fertilizer                float64
Pesticide                 float64
Yield                     float64
dtype: object
           Crop  Crop_Year       Season  State     Area  Production  \
0      Arecanut 1997-01-01  Whole Year   Assam  73814.0       56708
1     Arhar/Tur 1997-01-01  Kharif       Assam   6637.0        4685
2   Castor seed 1997-01-01  Kharif       Assam    796.0          22
3      Coconut  1997-01-01  Whole Year   Assam  19656.0   126905000
4  Cotton(lint) 1997-01-01  Kharif       Assam   1739.0         794

   Annual_Rainfall  Fertilizer  Pesticide        Yield
0           2051.4  7024878.38   22882.34     0.796087
1           2051.4   631643.29    2057.47     0.710435
2           2051.4    75755.32     246.76     0.238333
3           2051.4  1870661.52    6093.36  5238.051739
4           2051.4   165500.63     539.09     0.420909

In [13]:
print(df.loc[0:4, ["Crop", "Season", "Yield"]])

           Crop       Season        Yield
0      Arecanut  Whole Year      0.796087
1     Arhar/Tur  Kharif          0.710435
2   Castor seed  Kharif          0.238333
3      Coconut   Whole Year   5238.051739
4  Cotton(lint)  Kharif          0.420909

In [14]:
print(df.iloc[0:5, 0:4])

           Crop  Crop_Year       Season  State
0      Arecanut 1997-01-01  Whole Year   Assam
1     Arhar/Tur 1997-01-01  Kharif       Assam
2   Castor seed 1997-01-01  Kharif       Assam
3      Coconut  1997-01-01  Whole Year   Assam
4  Cotton(lint) 1997-01-01  Kharif       Assam

In [17]:
print(df.loc[:, "Crop"])

0             Arecanut
1            Arhar/Tur
2          Castor seed
3             Coconut
4         Cotton(lint)
             ...
19684    Small millets
19685            Wheat
19686            Maize
19687             Rice
19688            Wheat
Name: Crop, Length: 19689, dtype: str

In [18]:
print(df.iloc[:5])

           Crop  Crop_Year       Season  State     Area  Production  \
0      Arecanut 1997-01-01  Whole Year   Assam  73814.0       56708
1     Arhar/Tur 1997-01-01  Kharif       Assam   6637.0        4685
2   Castor seed 1997-01-01  Kharif       Assam    796.0          22
3      Coconut  1997-01-01  Whole Year   Assam  19656.0   126905000
4  Cotton(lint) 1997-01-01  Kharif       Assam   1739.0         794

   Annual_Rainfall  Fertilizer  Pesticide        Yield
0           2051.4  7024878.38   22882.34     0.796087
1           2051.4   631643.29    2057.47     0.710435
2           2051.4    75755.32     246.76     0.238333
3           2051.4  1870661.52    6093.36  5238.051739
4           2051.4   165500.63     539.09     0.420909

In [19]:
print(df[df["Yield"] > 1])

           Crop  Crop_Year       Season              State      Area  \
3      Coconut  1997-01-01  Whole Year               Assam   19656.0
7          Jute 1997-01-01  Kharif                   Assam   94520.0
10        Mesta 1997-01-01  Kharif                   Assam    5915.0
12        Onion 1997-01-01  Whole Year               Assam    7832.0
14       Potato 1997-01-01  Whole Year               Assam   75259.0
...         ...        ...          ...                ...       ...
19682     Maize 1998-01-01  Kharif                Nagaland   30000.0
19683      Rice 1998-01-01  Kharif                Nagaland  141000.0
19685     Wheat 1998-01-01  Rabi                  Nagaland    1000.0
19686     Maize 1997-01-01  Kharif       Jammu and Kashmir  310883.0
19688     Wheat 1997-01-01  Rabi         Jammu and Kashmir  239344.0

       Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
3       126905000           2051.4   1870661.52    6093.36  5238.051739
7          904095           2051.4   8995468.40   29301.20     9.919565
10          29003           2051.4    562930.55    1833.65     4.568947
12          17943           2051.4    745371.44    2427.92     2.342609
14         671871           2051.4   7162399.03   23330.29     7.561304
...           ...              ...          ...        ...          ...
19682       37000           1498.0   2964000.00    8700.00     1.225714
19683      205000           1498.0  13930800.00   40890.00     1.441429
19685        3000           1498.0     98800.00     290.00     3.000000
19686      440900           1356.2  29586735.11   96373.73     1.285000
19688      392160           1356.2  22778368.48   74196.64     1.261818

[10118 rows x 10 columns]

In [20]:
print(df[df["Crop"] == "Coconut"])

Empty DataFrame
Columns: [Crop, Crop_Year, Season, State, Area, Production, Annual_Rainfall, Fertilizer, Pesticide, Yield]
Index: []

In [21]:
print(df[(df["Yield"] > 1) & (df["Area"] > 1000)])

           Crop  Crop_Year       Season              State      Area  \
3      Coconut  1997-01-01  Whole Year               Assam   19656.0
7          Jute 1997-01-01  Kharif                   Assam   94520.0
10        Mesta 1997-01-01  Kharif                   Assam    5915.0
12        Onion 1997-01-01  Whole Year               Assam    7832.0
14       Potato 1997-01-01  Whole Year               Assam   75259.0
...         ...        ...          ...                ...       ...
19681      Jute 1998-01-01  Kharif                Nagaland   35000.0
19682     Maize 1998-01-01  Kharif                Nagaland   30000.0
19683      Rice 1998-01-01  Kharif                Nagaland  141000.0
19686     Maize 1997-01-01  Kharif       Jammu and Kashmir  310883.0
19688     Wheat 1997-01-01  Rabi         Jammu and Kashmir  239344.0

       Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
3       126905000           2051.4   1870661.52    6093.36  5238.051739
7          904095           2051.4   8995468.40   29301.20     9.919565
10          29003           2051.4    562930.55    1833.65     4.568947
12          17943           2051.4    745371.44    2427.92     2.342609
14         671871           2051.4   7162399.03   23330.29     7.561304
...           ...              ...          ...        ...          ...
19681       48000           1498.0   3458000.00   10150.00     1.370000
19682       37000           1498.0   2964000.00    8700.00     1.225714
19683      205000           1498.0  13930800.00   40890.00     1.441429
19686      440900           1356.2  29586735.11   96373.73     1.285000
19688      392160           1356.2  22778368.48   74196.64     1.261818

[8290 rows x 10 columns]

In [22]:
df["Production_Per_Area"] = df["Production"] / df["Area"]

In [23]:
print(df[["Crop", "Production", "Area", "Production_Per_Area"]].head())

           Crop  Production     Area  Production_Per_Area
0      Arecanut       56708  73814.0             0.768255
1     Arhar/Tur        4685   6637.0             0.705891
2   Castor seed          22    796.0             0.027638
3      Coconut    126905000  19656.0          6456.298331
4  Cotton(lint)         794   1739.0             0.456584

In [24]:
print(df.groupby("Crop")["Yield"].mean())

Crop
Arecanut                    2.073635
Arhar/Tur                   0.967348
Bajra                       2.427462
Banana                     26.851128
Barley                      1.595540
Black pepper                0.829605
Cardamom                    0.168355
Cashewnut                   3.120438
Castor seed                 0.693609
Coconut                  8652.000199
Coriander                   0.648200
Cotton(lint)                1.797044
Cowpea(Lobia)               0.813224
Dry chillies                2.078330
Garlic                      4.544886
Ginger                      6.442202
Gram                        0.876469
Groundnut                   1.360983
Guar seed                   0.951875
Horse-gram                  0.462822
Jowar                       1.072498
Jute                        7.555393
Khesari                     0.788941
Linseed                     0.473930
Maize                       3.427216
Masoor                      0.703153
Mesta                       5.389204
Moong(Green Gram)           0.530940
Moth                        0.445995
Niger seed                  0.423523
Oilseeds total              1.995559
Onion                      13.247525
Other  Rabi pulses          0.780380
Other Cereals               0.849546
Other Kharif pulses         0.699513
Other Summer Pulses         0.859925
Peas & beans (Pulses)       1.393895
Potato                     13.331718
Ragi                        1.215408
Rapeseed &Mustard           0.791568
Rice                        2.218495
Safflower                   0.565482
Sannhamp                    1.274959
Sesamum                     0.611750
Small millets               0.768722
Soyabean                    1.083194
Sugarcane                  51.727439
Sunflower                   0.934086
Sweet potato                9.240788
Tapioca                    16.667301
Tobacco                     2.110708
Turmeric                    3.325392
Urad                        0.584048
Wheat                       2.005086
other oilseeds              1.789220
Name: Yield, dtype: float64

In [25]:
print(df.groupby("State")["Production"].sum())

State
Andhra Pradesh        26076218605
Arunachal Pradesh         9522010
Assam                  3637714928
Bihar                   544953534
Chhattisgarh            143096606
Delhi                     2666022
Goa                    2193998349
Gujarat                 807581678
Haryana                 589739640
Himachal Pradesh         32297151
Jammu and Kashmir        30298377
Jharkhand                43793850
Karnataka             63772797366
Kerala               129700649853
Madhya Pradesh          834490323
Maharashtra            1878564915
Manipur                  18764635
Meghalaya                16516629
Mizoram                   2769208
Nagaland                 18748702
Odisha                  194080325
Puducherry              493815573
Punjab                  781551409
Sikkim                    2744927
Tamil Nadu            78051759253
Telangana               147700034
Tripura                  16952054
Uttar Pradesh          4442585302
Uttarakhand             179697348
West Bengal            8941179120
Name: Production, dtype: int64

In [26]:
print(df.groupby("Season")["Yield"].agg(
    ["min", "max", "sum", "mean", "count"]
))

                  min           max           sum        mean  count
Season
Autumn       0.156875    989.870000  1.621838e+03    3.917482    414
Kharif       0.000000    381.420000  2.043184e+04    2.482002   8232
Rabi         0.000000     80.268000  1.141807e+04    1.988518   5742
Summer       0.000000     69.366667  3.581857e+03    2.997370   1195
Whole Year   0.000000  21105.000000  1.535104e+06  412.995463   3717
Winter       0.113000     68.230000  2.056747e+03    5.287267    389

In [27]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Crop_Encoded"] = le.fit_transform(df["Crop"])

print(df[["Crop", "Crop_Encoded"]].head())

           Crop  Crop_Encoded
0      Arecanut             0
1     Arhar/Tur             1
2   Castor seed             8
3      Coconut              9
4  Cotton(lint)            11

In [28]:
print("Final Encoded DataFrame:")
print(df.head())

print("Original dataset shape: (19689, 10)")
print("Final dataset shape:", df.shape)

Final Encoded DataFrame:
           Crop  Crop_Year       Season  State     Area  Production  \
0      Arecanut 1997-01-01  Whole Year   Assam  73814.0       56708
1     Arhar/Tur 1997-01-01  Kharif       Assam   6637.0        4685
2   Castor seed 1997-01-01  Kharif       Assam    796.0          22
3      Coconut  1997-01-01  Whole Year   Assam  19656.0   126905000
4  Cotton(lint) 1997-01-01  Kharif       Assam   1739.0         794

   Annual_Rainfall  Fertilizer  Pesticide        Yield  Production_Per_Area  \
0           2051.4  7024878.38   22882.34     0.796087             0.768255
1           2051.4   631643.29    2057.47     0.710435             0.705891
2           2051.4    75755.32     246.76     0.238333             0.027638
3           2051.4  1870661.52    6093.36  5238.051739          6456.298331
4           2051.4   165500.63     539.09     0.420909             0.456584

   Crop_Encoded
0             0
1             1
2             8
3             9
4            11
Original dataset shape: (19689, 10)
Final dataset shape: (19689, 12)